/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui.java;

import com.dbc.java.DBConnection1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dinis
 */
public class DepartmentDetails extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public DepartmentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        viewbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        homebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtdeptcode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthead = new javax.swing.JTextField();
        txtlocation = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtdept_code = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(248, 240, 227));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gui/java/adminHL.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 10, 120, 130);

        viewbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });
        jPanel2.add(viewbtn);
        viewbtn.setBounds(570, 0, 120, 40);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Department Details");

        logoutbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        homebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homebtn.setText("Home");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 674, Short.MAX_VALUE)
                .addComponent(homebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutbtn)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutbtn)
                    .addComponent(homebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(120, 40, 1230, 70);

        jLabel1.setBackground(new java.awt.Color(248, 240, 227));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, -10, 1470, 130);

        addbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel2.add(addbtn);
        addbtn.setBounds(180, 0, 120, 40);

        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel2.add(updatebtn);
        updatebtn.setBounds(310, 0, 120, 40);

        deletebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel2.add(deletebtn);
        deletebtn.setBounds(440, 0, 120, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Dept. Code");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(240, 180, 100, 30);

        txtdeptcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdeptcode.setText("dp_00");
        jPanel2.add(txtdeptcode);
        txtdeptcode.setBounds(380, 180, 170, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Dept. Name");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 250, 100, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtname);
        txtname.setBounds(380, 250, 170, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Dept. Head");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(240, 320, 100, 30);

        txthead.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txthead);
        txthead.setBounds(380, 320, 170, 30);

        txtlocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<select>", "A block", "B block", "C block" }));
        jPanel2.add(txtlocation);
        txtlocation.setBounds(380, 390, 170, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Location");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(240, 400, 100, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Dept. Code");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(890, 130, 100, 30);

        txtdept_code.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdept_code.setText("dp_00");
        jPanel2.add(txtdept_code);
        txtdept_code.setBounds(1000, 130, 170, 30);

        searchbtn.setBackground(new java.awt.Color(0, 204, 255));
        searchbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchbtn);
        searchbtn.setBounds(1200, 130, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        new AdminHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        this.dispose();
        ViewDepartment vde = new ViewDepartment();
        vde.setVisible(true);
        vde.setLocationRelativeTo(null);
    }//GEN-LAST:event_viewbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
       String dept_code = txtdeptcode.getText();
       String name = txtname.getText();
       String head = txthead.getText();
       String location = txtlocation.getSelectedItem().toString();
       
       String sql = "insert into departments(dept_code,name,head,location) values(?,?,?,?)";
       
       try {
           Connection con = DBConnection1.getDBConnection1();
           PreparedStatement  stmt = con.prepareStatement(sql);
            stmt.setString(1,dept_code);
            stmt.setString(2, name);
            stmt.setString(3, head);
            stmt.setString(4, location);
           
            int status = stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Department Added Successful!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "This code is already used!");
            System.out.println(e);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       String dept_code = txtdeptcode.getText();
       String name = txtname.getText();
       String head = txthead.getText();
       String location = txtlocation.getSelectedItem().toString();
       
       String sql = "update departments set dept_code =?,name =?,head =?,location =? where dept_code =? ";
       
       try {
           Connection con = DBConnection1.getDBConnection1();
           PreparedStatement  stmt = con.prepareStatement(sql);
            stmt.setString(1,dept_code);
            stmt.setString(2, name);
            stmt.setString(3, head);
            stmt.setString(4, location);
            stmt.setString(5, dept_code);
           
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Department Added Successful!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "This code is already used!");
            System.out.println(e);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String dept_code = txtdeptcode.getText();
        String sql = "delete from departments where  dept_code = ?";
           try {
            int deleteStatus = JOptionPane.showConfirmDialog(null, "Do you want to delete the Department " +dept_code+ " !");
            if(deleteStatus == 0){
               Connection con = DBConnection1.getDBConnection1();
               PreparedStatement psmt = con.prepareStatement(sql);
               psmt.setString(1, dept_code);
               int status = psmt.executeUpdate();
               JOptionPane.showMessageDialog(null, "The department has beeen deleted!");
               System.out.println(deleteStatus);
              }
    
           } catch (Exception e) {
               System.out.println(e);
           }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
         String dept_code = txtdept_code.getText();
        
       
          String update = "select * from departments where dept_code = ?";
            try {
                Connection con = DBConnection1.getDBConnection1();
                PreparedStatement psmt = con.prepareStatement(update);
                psmt.setString(1, dept_code);
                ResultSet rs = psmt.executeQuery();
              
                if(rs.next()){
              
                txtdeptcode.setText(rs.getString("dept_code"));
                txtname.setText(rs.getString("name"));
                txthead.setText(rs.getString("head"));
                txtlocation.setSelectedItem(rs.getString("location"));
               
                }else{
                    JOptionPane.showMessageDialog(null, "Department code does not match");
                }
                setVisible(true);
            } catch (Exception e) {
                System.out.println(e);
            }
  
    
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField txtdept_code;
    private javax.swing.JTextField txtdeptcode;
    private javax.swing.JTextField txthead;
    private javax.swing.JComboBox txtlocation;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
